# �Ƿ����� Dataway ���ܣ���ѡ��Ĭ��false��
HASOR_DATAQL_DATAWAY: true

# �Ƿ��� Dataway ��̨������棨��ѡ��Ĭ��false��
HASOR_DATAQL_DATAWAY_ADMIN: true

# dataway  API����·������ѡ��Ĭ�ϣ�/api/��
HASOR_DATAQL_DATAWAY_API_URL: /api/

# dataway-ui �Ĺ���·������ѡ��Ĭ�ϣ�/interface-ui/��
HASOR_DATAQL_DATAWAY_UI_URL: /interface-ui/

spring:
  #���ݿ�����
  datasource:
    url: jdbc:mysql://localhost:3306/dataway?useUnicode=true&characterEncoding=UTF-8&verifyServerCertificate=false&useSSL=false&requireSSL=false&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2B8
    username: root
    password: zyl123
    type: com.alibaba.druid.pool.DruidDataSource
    filters: stat,slf4j
    initialSize: 10
    maxActive: 100
    maxWait: 60000
    minIdle: 5300000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis:
    validationQuery: SELECT 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    driver-class-name: com.mysql.cj.jdbc.Driver #8.0
